# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "31ef8dcd9586021f76d3de78510465c8"
name = "Retail Express-Click & Collect"
handle = "retail-express-click-collect"
application_url = "https://waves-exemption-salon-yarn.trycloudflare.com/"
embedded = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locales,read_locations,read_product_listings,read_products,read_publications,read_script_tags,write_content,write_inventory,write_locations,write_products,write_publications,write_script_tags,write_shipping"

[auth]
redirect_urls = [
  "https://waves-exemption-salon-yarn.trycloudflare.com/auth/callback",
  "https://waves-exemption-salon-yarn.trycloudflare.com/auth/shopify/callback",
  "https://waves-exemption-salon-yarn.trycloudflare.com/api/auth/callback",
  "https://waves-exemption-salon-yarn.trycloudflare.com/api/auth"
]

[pos]
embedded = false

[app_preferences]
url = "https://waves-exemption-salon-yarn.trycloudflare.com/"

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true
