# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "511a7091545642e9583302831a7bdebf"
name = "sdev-click-and-collect"
handle = "sdev-click-and-collect-2"
application_url = "https://star-legend-fabrics-swap.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locales,read_locations,read_orders,read_product_listings,read_products,read_publications,read_script_tags,write_content,write_inventory,write_locations,write_products,write_publications,write_script_tags,write_shipping"

[auth]
redirect_urls = ["https://star-legend-fabrics-swap.trycloudflare.com/auth/callback", "https://star-legend-fabrics-swap.trycloudflare.com/auth/shopify/callback", "https://star-legend-fabrics-swap.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
